// application.yml for account-service
server:
  port: 8082

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/accountdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/